# Copyright (C) 2016 Jurriaan Bremer.
# This file is part of SFlock - http://www.sflock.org/.
# See the file 'docs/LICENSE.txt' for copying permission.

from sflock.abstracts import File

def test_package():
    assert File("a.pdf").package == "pdf"
    assert File("a.rtf").package == "doc"
    assert File("a.doc").package == "doc"
    assert File("a.docx").package == "doc"
    assert File("a.docm").package == "doc"
    assert File("a.dot").package == "doc"
    assert File("a.dotx").package == "doc"
    assert File("a.docb").package == "doc"
    assert File("a.mht").package == "doc"
    assert File("a.mso").package == "doc"
    assert File("a.xls").package == "xls"
    assert File("a.xlsx").package == "xls"
    assert File("a.xlm").package == "xls"
    assert File("a.xlsx").package == "xls"
    assert File("a.xlt").package == "xls"
    assert File("a.xltx").package == "xls"
    assert File("a.xlsm").package == "xls"
    assert File("a.xltm").package == "xls"
    assert File("a.xlsb").package == "xls"
    assert File("a.xla").package == "xls"
    assert File("a.xlam").package == "xls"
    assert File("a.xll").package == "xls"
    assert File("a.xlw").package == "xls"
    assert File("a.ppt").package == "ppt"
    assert File("a.pptx").package == "ppt"
    assert File("a.pps").package == "ppt"
    assert File("a.ppsx").package == "ppt"
    assert File("a.pptm").package == "ppt"
    assert File("a.potm").package == "ppt"
    assert File("a.potx").package == "ppt"
    assert File("a.ppsm").package == "ppt"
    assert File("a.pot").package == "ppt"
    assert File("a.ppam").package == "ppt"
    assert File("a.sldx").package == "ppt"
    assert File("a.sldm").package == "ppt"
    assert File("a.pub").package == "pub"
    assert File("a.jar").package == "jar"
    assert File("a.py").package == "python"
    assert File("a.pyc").package == "python"
    assert File("a.pyo").package == "python"
    assert File("a.vbs").package == "vbs"
    assert File("a.js").package == "js"
    assert File("a.jse").package == "js"
    assert File("a.msi").package == "msi"
    assert File("a.ps1").package == "ps1"
    assert File("a.ps1xml").package == "ps1"
    assert File("a.psc1").package == "ps1"
    assert File("a.psm1").package == "ps1"
    assert File("a.wsf").package == "wsf"
    assert File("a.htm").package == "ie"
    assert File("a.html").package == "ie"

def test_case():
    assert File("A.PDF").package == "pdf"
    assert File("A.RTF").package == "doc"
    assert File("A.DOC").package == "doc"
    assert File("A.PUB").package == "pub"
    assert File("A.JAR").package == "jar"
